// Builds the site into dist/. Zero dependencies: plain Node 18 or newer.
//   node build.mjs
// Content lives in content/*.json; templates in src/; static files in public/.

import { readFile, writeFile, mkdir, cp, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { renderHome, renderMenuPage, renderDashboard } from './src/render.mjs';
import { buildCatalog } from './src/order-core.mjs';
import { art } from './src/icons.mjs';

const root = new URL('./', import.meta.url);
const readJson = async (p) => JSON.parse(await readFile(new URL(p, root), 'utf8'));

const site = await readJson('content/site.json');
const menu = await readJson('content/menu.json');
check(site, menu);

const fingerprint = async (p) =>
  createHash('sha256').update(await readFile(new URL(p, root))).digest('hex').slice(0, 10);
const assets = {
  css: await fingerprint('public/styles.css'),
  js: await fingerprint('public/app.js'),
  order: await fingerprint('public/order.js'),
  dash: await fingerprint('public/dashboard.js'),
  dashCss: await fingerprint('public/dashboard.css'),
};

// Online ordering. Fails closed: the cart only appears when the owner has
// switched it on in content/site.json AND Supabase is configured in the
// host's environment variables. The anon/publishable key is public by
// design (row level security does the guarding); the service key is read
// only by the order function at runtime, never here.
const env = process.env;
const supabaseUrl = env.SUPABASE_URL?.trim();
const supabaseAnonKey = (env.SUPABASE_ANON_KEY || env.SUPABASE_PUBLISHABLE_KEY)?.trim();
const catalog = buildCatalog(menu);
const orderingOn = Boolean(site.ordering && supabaseUrl);
if (site.ordering && !supabaseUrl) console.warn('Ordering is on in site.json but SUPABASE_URL is not set: the cart stays hidden.');
const orderData = orderingOn
  ? { endpoint: '/api/order', catalog, timezone: site.timezone, hours: site.hours, phone: site.phone }
  : null;
const dashboardConfig =
  supabaseUrl && supabaseAnonKey ? { url: supabaseUrl, key: supabaseAnonKey, timezone: site.timezone } : null;

// The order function's own copy of the menu and hours, so it prices and
// times every order itself.
await writeFile(
  new URL('netlify/functions/order/catalog.generated.mjs', root),
  `// Generated by build.mjs from content/. Do not edit.\nexport const catalog = ${JSON.stringify(catalog)};\nexport const site = ${JSON.stringify({ ordering: orderingOn, phone: site.phone, timezone: site.timezone, hours: site.hours })};\n`,
);

const out = new URL('dist/', root);
await rm(out, { recursive: true, force: true });
await cp(new URL('public/', root), out, { recursive: true });
await writeFile(new URL('index.html', out), renderHome({ site, menu, assets, orderData }));
await mkdir(new URL('menu/', out), { recursive: true });
await writeFile(new URL('menu/index.html', out), renderMenuPage({ site, menu, assets, orderData }));
await mkdir(new URL('dashboard/', out), { recursive: true });
await writeFile(new URL('dashboard/index.html', out), renderDashboard({ site, assets, dashboardConfig }));

if (!site.preview) {
  await writeFile(new URL('robots.txt', out), `User-agent: *\nAllow: /\n\nSitemap: ${site.url}/sitemap.xml\n`);
  await writeFile(
    new URL('sitemap.xml', out),
    `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${site.url}/</loc></url>
  <url><loc>${site.url}/menu/</loc></url>
</urlset>
`,
  );
}

const items = menu.sections.reduce((n, s) => n + s.items.length, 0);
console.log(
  `Built dist/: 2 pages, ${menu.sections.length} menu sections, ${items} items.` +
    (site.preview ? ' PREVIEW mode: pages are marked noindex.' : '') +
    ` Online ordering ${orderingOn ? 'ON' : 'off'}; dashboard ${dashboardConfig ? 'configured' : 'not configured'}.`,
);

// Catch the mistakes a quick content edit is likely to make, before they ship.
function check(site, menu) {
  const problems = [];
  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
  const time = /^([01]\d|2[0-3]):[0-5]\d$/;

  if (site.hours.length !== 7) problems.push('hours must list all seven days');
  for (const d of site.hours) {
    if (!days.includes(d.day)) problems.push(`hours: unknown day "${d.day}"`);
    if (d.closed) continue;
    if (!time.test(d.open ?? '') || !time.test(d.close ?? '')) {
      problems.push(`hours: ${d.day} times must be 24-hour like "06:00" and "14:00"`);
    } else if (d.open >= d.close) {
      problems.push(`hours: ${d.day} opens after it closes`);
    }
  }
  if (!/^\+1\d{10}$/.test(site.phoneE164)) problems.push('phoneE164 must look like +18125551234');

  const ids = new Set();
  for (const s of menu.sections) {
    if (!/^[a-z0-9-]+$/.test(s.id)) problems.push(`menu: section id "${s.id}" must be lowercase-with-dashes`);
    if (ids.has(s.id)) problems.push(`menu: section id "${s.id}" is used twice`);
    ids.add(s.id);
    const priceOk = (v) => /^\$?\d+(\.\d{2})?$/.test(String(v));
    if (s.price && !priceOk(s.price)) problems.push(`menu: "${s.title}" price "${s.price}" should look like 6.49`);
    for (const i of s.items) {
      if (!i.name) problems.push(`menu: an item in "${s.title}" has no name`);
      const all = [...(i.price ? [i.price] : []), ...(i.prices ?? []).map((p) => p.price)];
      for (const v of all) if (!priceOk(v)) problems.push(`menu: ${i.name} price "${v}" should look like 6.49`);
    }
  }
  for (const f of menu.favorites) {
    if (!art[f.icon]) problems.push(`favorites: no drawing called "${f.icon}" (have: ${Object.keys(art).join(', ')})`);
  }

  // House rule: no em dashes anywhere a person reads.
  if (JSON.stringify([site, menu]).includes('\u2014')) {
    problems.push('an em dash slipped into the content; use a period, comma or colon instead');
  }

  if (problems.length) {
    console.error(`Content problems:\n - ${problems.join('\n - ')}`);
    process.exit(1);
  }
}
